FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server

# Install app dependencies
COPY package.json /usr/src/server
RUN npm install

# Bundle app source
COPY app /usr/src/server

EXPOSE 8080
CMD [ "npm", "start" ]